# ─── PII Shield – Sample Demo Data ────────────────────────────────────────────
# This file provides realistic (but synthetic) PII data for testing.
# NONE of these are real people. All SSNs/cards generated by checksum tools.

SAMPLE_EMAIL_TEXT = """
Dear Support,

Please update my account with the following information:

Full Name: Sarah J. Miller
Email: sarah.miller@globalcorp.io
Phone: (415) 555-0198
Date of Birth: 1985-07-14
SSN: 219-09-9999
Credit Card: 4539 1488 0343 6467  (Visa – exp 03/27)
Passport: X12345678
Address: 742 Evergreen Terrace, Springfield, IL 62704

I also need to update my billing address for our EU subsidiary:
Contact: Hans Müller, hans.mueller@eurocorp.de
IBAN: DE89370400440532013000
IP from last login: 192.168.1.42

Best regards,
Sarah Miller
"""

SAMPLE_LOG_TEXT = """
2024-01-15T10:23:45Z INFO  [auth-service] Login attempt for user=admin@company.com from ip=10.0.0.15
2024-01-15T10:23:46Z WARN  [auth-service] MFA bypass detected – user=admin@company.com token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIn0.dozjgNryP4J3jVmNHl0w5N_XgL0n3I9PlFUP0THsR8U
2024-01-15T10:24:01Z ERROR [payment-service] Payment failed for card=4532015112830366 cvv=123 amount=499.99
2024-01-15T10:24:02Z DEBUG [user-service] Updated profile: name="John Doe" ssn=078-05-1120 dob=1990-03-21
2024-01-15T10:24:03Z INFO  [api-gateway] API key used: sk-proj-abc123def456ghi789jkl012mno345pqr678stu901
2024-01-15T10:24:04Z WARN  [db-service] Query contains PII: SELECT * FROM users WHERE email='jane.doe@example.com' AND phone='+1-212-555-0147'
"""

SAMPLE_MEDICAL_TEXT = """
Patient Name: Robert A. Chen
DOB: 1972-11-03
MRN: 98765432
SSN: 219-09-9999

Diagnosis: Type 2 Diabetes Mellitus (E11.9)
Medications: Metformin 500mg BID, Lisinopril 10mg daily
Allergies: Penicillin (anaphylaxis)

Lab Results (2024-01-10):
  HbA1c: 7.2%
  Fasting Glucose: 142 mg/dL
  Creatinine: 1.1 mg/dL

Insurance: BlueCross BlueShield
Policy #: BCB-2024-88776655
Group #: GRP-44231

Provider: Dr. Emily Watson
NPI: 1234567890
Contact: ewatson@medhospital.org
Phone: (312) 555-0234
"""

SAMPLE_FINANCIAL_TEXT = """
Account Statement – January 2024

Account Holder: Michael J. Thompson
Account Number: 8834-2291-0045-6723
Routing Number: 021000021

Transactions:
  01/05 - Wire Transfer to IBAN GB82WEST12345698765432 – £5,000.00
  01/12 - POS Purchase at Amazon – Card ending 6467 – $234.99
  01/15 - ACH Deposit from GlobalCorp – $8,450.00 (Ref: PAY-2024-0115)
  01/20 - ATM Withdrawal – $500.00

Tax ID (EIN): 12-3456789

For questions, contact:
  Email: support@megabank.com
  Phone: 1-800-555-0199
  PAN: ABCPD1234E
"""

SAMPLE_CODE_SNIPPET = """
# WARNING: Hardcoded credentials detected
import os
DATABASE_URL = "postgresql://admin:SuperSecret123!@db.prod.internal:5432/userdata"
API_KEY = "sk-proj-abc123def456ghi789jkl012mno345pqr678stu901"
AWS_SECRET_KEY = "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"

# Private key embedded in source
PRIVATE_KEY = \"\"\"-----BEGIN RSA PRIVATE KEY-----
MIIEowIBAAKCAQEA2a2rwplBQLkF0MKXaL7hSE9IKXCm8aFz1RiNfaGBHblKQ0nd
...truncated for demo...
-----END RSA PRIVATE KEY-----\"\"\"
"""

CLEAN_TEXT = """
The Quick Brown Fox Jumps Over The Lazy Dog.
Today the temperature is 72°F with clear skies.
Our quarterly revenue increased by 15% compared to last year.
The meeting is scheduled for January 25, 2024 at 3:00 PM EST.
Please review the attached proposal (Document ID: DOC-2024-0125).
"""

# ─── Summary of PII Types Present in Demo Data ─────────────────────
DEMO_PII_MAP = {
    "email_text": {
        "emails": ["sarah.miller@globalcorp.io", "hans.mueller@eurocorp.de"],
        "phones": ["(415) 555-0198"],
        "ssns": ["219-09-9999"],
        "credit_cards": ["4539 1488 0343 6467"],
        "names": ["Sarah J. Miller", "Hans Müller"],
        "addresses": ["742 Evergreen Terrace, Springfield, IL 62704"],
        "ips": ["192.168.1.42"],
    },
    "log_text": {
        "emails": ["admin@company.com", "jane.doe@example.com"],
        "credit_cards": ["4532015112830366"],
        "ssns": ["078-05-1120"],
        "api_keys": ["sk-proj-abc123def456ghi789jkl012mno345pqr678stu901"],
        "jwts": 1,
    },
    "medical_text": {
        "ssns": ["219-09-9999"],
        "emails": ["ewatson@medhospital.org"],
        "phones": ["(312) 555-0234"],
        "names": ["Robert A. Chen", "Dr. Emily Watson"],
    },
    "financial_text": {
        "emails": ["support@megabank.com"],
        "phones": ["1-800-555-0199"],
        "pans": ["ABCPD1234E"],
        "names": ["Michael J. Thompson"],
    },
    "code_snippet": {
        "api_keys": 1,
        "passwords": 1,
        "private_keys": 1,
    },
    "clean_text": {
        "expected_pii_count": 0,
    },
}
